version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - govet
  exclusions:
    generated: lax
    presets:
      - common-false-positives
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - goimports
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
